import "../styles/globals.css";
import type { AppProps } from "next/app";
import { Provider as ReduxProvider } from "react-redux";

import Head from "next/head";

import { StyledEngineProvider } from "@mui/material/styles";
import Snackbar from "@/components/@extended/Snackbar";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { store } from "@/store";

export default function App(props: AppProps) {
  const { Component, pageProps, router } = props;
  const shouldRenderLayout = !["/login"].includes(router.pathname);

  return (
    <>
      <Head>
        <title>ECOM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/AivaLogo.svg" />
      </Head>

      <StyledEngineProvider injectFirst>
        <ReduxProvider store={store}>
          {/* <AuthProvider> */}
            {shouldRenderLayout && <Header />}
            <Component {...pageProps} />
            {shouldRenderLayout && <Footer />}
            <Snackbar />
          {/* </AuthProvider> */}
        </ReduxProvider>
      </StyledEngineProvider>
    </>
  );
}
